st.image("crime_dashboard/figure1.png", use_container_width=True)
st.image("crime_dashboard/figure2.png", use_container_width=True)
st.image("crime_dashboard/figure3.png", use_container_width=True)
st.image("crime_dashboard/figure4.png", use_container_width=True)
st.image("crime_dashboard/figure5.png", use_container_width=True)
st.image("crime_dashboard/figure6.png", use_container_width=True)
st.image("crime_dashboard/figure7.png", use_container_width=True)
st.image("crime_dashboard/figure8.png", use_container_width=True)
